"""add_reporting_period_risk_technical_report

Revision ID: 0cb398fdb356
Revises: ae5e237e9868
Create Date: 2026-03-12 21:09:27.058792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb398fdb356'
down_revision: Union[str, None] = 'ae5e237e9868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_periods',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('period_type', postgresql.ENUM('PERIODIC', 'FINAL', name='reporting_period_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('technical_report_deadline', sa.Date(), nullable=False),
    sa.Column('financial_report_deadline', sa.Date(), nullable=True),
    sa.Column('review_meeting_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_periods_project_id'), 'reporting_periods', ['project_id'], unique=False)
    op.create_table('report_reminders',
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', postgresql.ENUM('T_90', 'T_60', 'T_45', 'T_30', 'T_20', 'T_15', 'T_7', name='reminder_type'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reminders_reporting_period_id'), 'report_reminders', ['reporting_period_id'], unique=False)
    op.create_table('risks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', postgresql.ENUM('TECHNICAL', 'FINANCIAL', 'ORGANIZATIONAL', 'EXTERNAL', name='risk_category_type'), nullable=False),
    sa.Column('probability', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='risk_level_type'), nullable=False),
    sa.Column('impact', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='risk_level_type'), nullable=False),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'MITIGATED', 'CLOSED', name='risk_status_type'), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_table('technical_reports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('report_type', postgresql.ENUM('PERIODIC', 'FINAL', name='reporting_period_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'WP_INPUT', 'PARTNER_REVIEW', 'CONSOLIDATION', 'INTERNAL_REVIEW', 'FINAL_REVIEW', 'SUBMITTED', 'EC_APPROVED', name='report_status_type'), nullable=False),
    sa.Column('part_a_summary', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ec_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_reports_project_id'), 'technical_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_technical_reports_reporting_period_id'), 'technical_reports', ['reporting_period_id'], unique=False)
    op.create_index(op.f('ix_technical_reports_status'), 'technical_reports', ['status'], unique=False)
    op.create_table('report_sections',
    sa.Column('technical_report_id', sa.UUID(), nullable=False),
    sa.Column('section_type', postgresql.ENUM('PART_A_SUMMARY', 'PART_B1_WP_NARRATIVE', 'PART_B2_DELIVERABLES', 'PART_B3_RISKS', 'PART_B4_RESOURCES', name='report_section_type'), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', name='report_section_status_type'), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technical_report_id'], ['technical_reports.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_technical_report_id'), 'report_sections', ['technical_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_sections_technical_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_technical_reports_status'), table_name='technical_reports')
    op.drop_index(op.f('ix_technical_reports_reporting_period_id'), table_name='technical_reports')
    op.drop_index(op.f('ix_technical_reports_project_id'), table_name='technical_reports')
    op.drop_table('technical_reports')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_report_reminders_reporting_period_id'), table_name='report_reminders')
    op.drop_table('report_reminders')
    op.drop_index(op.f('ix_reporting_periods_project_id'), table_name='reporting_periods')
    op.drop_table('reporting_periods')
    # ### end Alembic commands ###
