"""add_financial_statement_wp_declaration_unit_delivery

Revision ID: 12405d09748a
Revises: 0cb398fdb356
Create Date: 2026-03-12 21:30:06.884512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12405d09748a'
down_revision: Union[str, None] = '0cb398fdb356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PARTNER_SUBMITTED', 'COORDINATOR_REVIEW', 'COORDINATOR_APPROVED', 'REPORTED_TO_EC', 'EC_APPROVED', name='financial_statement_status_type'), nullable=False),
    sa.Column('category_a_personnel', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category_b_subcontracting', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category_c_travel', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category_d_equipment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category_e_other', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_direct_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('indirect_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_eligible_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ec_contribution_requested', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cumulative_claimed', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cfs_required', sa.Boolean(), nullable=False),
    sa.Column('cfs_status', postgresql.ENUM('NOT_REQUIRED', 'PENDING', 'OBTAINED', 'SUBMITTED', name='cfs_status_type'), nullable=False),
    sa.Column('partner_signed_by', sa.String(length=200), nullable=True),
    sa.Column('partner_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coordinator_approved_by', sa.String(length=200), nullable=True),
    sa.Column('coordinator_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_to_ec_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('university_report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_partner_id'), 'financial_statements', ['partner_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_project_id'), 'financial_statements', ['project_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_reporting_period_id'), 'financial_statements', ['reporting_period_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_status'), 'financial_statements', ['status'], unique=False)
    op.create_table('unit_delivery_records',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_type', postgresql.ENUM('PERSON_DAY', 'PERSON_MONTH', 'TRAINING_HOUR', 'PUBLICATION', 'DATASET', 'PROTOTYPE', 'EVENT', 'LICENCE', 'OTHER', name='unit_type_type'), nullable=False),
    sa.Column('planned_units', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_units', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'REPORTED', 'APPROVED', name='unit_cost_status_type'), nullable=False),
    sa.Column('evidence_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(length=200), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_delivery_records_project_id'), 'unit_delivery_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_unit_delivery_records_reporting_period_id'), 'unit_delivery_records', ['reporting_period_id'], unique=False)
    op.create_index(op.f('ix_unit_delivery_records_work_package_id'), 'unit_delivery_records', ['work_package_id'], unique=False)
    op.create_table('wp_completion_declarations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=False),
    sa.Column('completion_status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', name='completion_status_type'), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('lump_sum_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_claimed', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('evidence_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partial_completion_justification', sa.Text(), nullable=True),
    sa.Column('deliverables_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('declared_by', sa.String(length=200), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wp_completion_declarations_project_id'), 'wp_completion_declarations', ['project_id'], unique=False)
    op.create_index(op.f('ix_wp_completion_declarations_reporting_period_id'), 'wp_completion_declarations', ['reporting_period_id'], unique=False)
    op.create_index(op.f('ix_wp_completion_declarations_work_package_id'), 'wp_completion_declarations', ['work_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wp_completion_declarations_work_package_id'), table_name='wp_completion_declarations')
    op.drop_index(op.f('ix_wp_completion_declarations_reporting_period_id'), table_name='wp_completion_declarations')
    op.drop_index(op.f('ix_wp_completion_declarations_project_id'), table_name='wp_completion_declarations')
    op.drop_table('wp_completion_declarations')
    op.drop_index(op.f('ix_unit_delivery_records_work_package_id'), table_name='unit_delivery_records')
    op.drop_index(op.f('ix_unit_delivery_records_reporting_period_id'), table_name='unit_delivery_records')
    op.drop_index(op.f('ix_unit_delivery_records_project_id'), table_name='unit_delivery_records')
    op.drop_table('unit_delivery_records')
    op.drop_index(op.f('ix_financial_statements_status'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_reporting_period_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_project_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_partner_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
