"""add_mission_workflow_fields

Revision ID: 47726d0e87e5
Revises: f321b32341cf
Create Date: 2026-03-12 18:58:20.542971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47726d0e87e5'
down_revision: Union[str, None] = 'f321b32341cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('estimated_total_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('missions', sa.Column('actual_total_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('missions', sa.Column('is_international', sa.Boolean(), nullable=False))
    op.add_column('missions', sa.Column('requires_central_approval', sa.Boolean(), nullable=False))
    op.add_column('missions', sa.Column('approved_by_pi_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('approved_centrally_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('missions', sa.Column('reconciliation_notes', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('actual_receipts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'actual_receipts')
    op.drop_column('missions', 'reconciliation_notes')
    op.drop_column('missions', 'completed_at')
    op.drop_column('missions', 'approved_centrally_at')
    op.drop_column('missions', 'approved_by_pi_at')
    op.drop_column('missions', 'requires_central_approval')
    op.drop_column('missions', 'is_international')
    op.drop_column('missions', 'actual_total_cost')
    op.drop_column('missions', 'estimated_total_cost')
    # ### end Alembic commands ###
