"""add_section9_additional_features

Revision ID: 623d9171f459
Revises: a860bea81ec0
Create Date: 2026-03-12 23:40:15.636416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '623d9171f459'
down_revision: Union[str, None] = 'a860bea81ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_definitions',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('INTEGER', 'DECIMAL', 'PERCENTAGE', 'BOOLEAN', 'TEXT', name='kpidatatype'), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('programme', sa.String(length=50), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('amendment_number', sa.Integer(), nullable=False),
    sa.Column('amendment_type', sa.Enum('BUDGET_TRANSFER', 'TIMELINE_CHANGE', 'PARTNER_CHANGE', 'SCOPE_CHANGE', 'OTHER', name='amendmenttype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='amendmentstatus'), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('ec_decision_date', sa.Date(), nullable=True),
    sa.Column('changes_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_partners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_work_packages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_records',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('expertise_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reliability_rating', sa.Integer(), nullable=True),
    sa.Column('collaboration_notes', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=300), nullable=True),
    sa.Column('contact_email', sa.String(length=300), nullable=True),
    sa.Column('co_publications', sa.Integer(), nullable=False),
    sa.Column('last_collaboration_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_management_records',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository', sa.String(length=300), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('dmp_status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'COMPLIANT', 'NON_COMPLIANT', name='dmpstatus'), nullable=False),
    sa.Column('fair_findable', sa.Boolean(), nullable=False),
    sa.Column('fair_accessible', sa.Boolean(), nullable=False),
    sa.Column('fair_interoperable', sa.Boolean(), nullable=False),
    sa.Column('fair_reusable', sa.Boolean(), nullable=False),
    sa.Column('data_format', sa.String(length=200), nullable=True),
    sa.Column('retention_period', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('REPORTING_DEADLINE', 'TIMESHEET_REMINDER', 'DELIVERABLE_DUE', 'BUDGET_THRESHOLD', 'CONTRACT_EXPIRY', 'AMENDMENT_STATUS', 'EC_FEEDBACK', 'PARTNER_PAYMENT', 'RISK_ESCALATION', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'READ', 'DISMISSED', name='notificationstatus'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_role', sa.String(length=100), nullable=True),
    sa.Column('recipient_email', sa.String(length=300), nullable=True),
    sa.Column('trigger_entity_type', sa.String(length=100), nullable=True),
    sa.Column('trigger_entity_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_values',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kpi_definition_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_decimal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['kpi_definitions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dissemination_activities',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Enum('PUBLICATION', 'CONFERENCE', 'PRESS_RELEASE', 'SOCIAL_MEDIA', 'WORKSHOP', 'POLICY_BRIEF', 'OTHER', name='disseminationactivitytype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('open_access_status', sa.Enum('NOT_APPLICABLE', 'GREEN', 'GOLD', 'DIAMOND', 'EMBARGO', 'NON_COMPLIANT', name='openaccessstatus'), nullable=False),
    sa.Column('target_audience', sa.String(length=300), nullable=True),
    sa.Column('countries_reached', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethics_requirements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('requirement_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'APPROVED', 'REJECTED', 'NOT_APPLICABLE', name='ethicsstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('ethics_committee_ref', sa.String(length=200), nullable=True),
    sa.Column('informed_consent_obtained', sa.Boolean(), nullable=False),
    sa.Column('dpia_required', sa.Boolean(), nullable=False),
    sa.Column('dpia_reference', sa.String(length=200), nullable=True),
    sa.Column('supporting_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_assets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('ip_type', sa.Enum('BACKGROUND', 'FOREGROUND', name='iptype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IDENTIFIED', 'DISCLOSED', 'PATENT_FILED', 'PATENT_GRANTED', 'LICENSED', 'EXPLOITED', name='ipstatus'), nullable=False),
    sa.Column('owner', sa.String(length=300), nullable=True),
    sa.Column('patent_reference', sa.String(length=200), nullable=True),
    sa.Column('patent_filing_date', sa.Date(), nullable=True),
    sa.Column('licensing_details', sa.Text(), nullable=True),
    sa.Column('exploitation_plan', sa.Text(), nullable=True),
    sa.Column('access_rights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_assets')
    op.drop_table('ethics_requirements')
    op.drop_table('dissemination_activities')
    op.drop_table('kpi_values')
    op.drop_table('notifications')
    op.drop_table('data_management_records')
    op.drop_table('collaboration_records')
    op.drop_table('amendments')
    op.drop_table('kpi_definitions')
    # ### end Alembic commands ###
