"""add_document_template_and_generated_document

Revision ID: a860bea81ec0
Revises: 12405d09748a
Create Date: 2026-03-12 22:07:03.823764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a860bea81ec0'
down_revision: Union[str, None] = '12405d09748a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', postgresql.ENUM('PERSONNEL', 'EC_CONSORTIUM', 'REPORTING', 'MISSION_TRAVEL', 'PROCUREMENT', name='template_category_type'), nullable=False),
    sa.Column('personnel_type', postgresql.ENUM('BOLSA_BI', 'BOLSA_BD', 'BOLSA_BPD', 'DL57', 'CEEC', 'CLT', 'CONTRACT_RENEWAL', name='personnel_template_type'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('field_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditional_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_cost_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_programmes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_category'), 'document_templates', ['category'], unique=False)
    op.create_index(op.f('ix_document_templates_slug'), 'document_templates', ['slug'], unique=True)
    op.create_table('generated_documents',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SIGNED', 'ARCHIVED', name='generated_document_status_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_project_id'), 'generated_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_researcher_id'), 'generated_documents', ['researcher_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_status'), 'generated_documents', ['status'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_template_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_status'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_researcher_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_project_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_document_templates_slug'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_category'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
