"""add_researcher_effort_timesheet

Revision ID: ae5e237e9868
Revises: 47726d0e87e5
Create Date: 2026-03-12 19:21:43.705674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae5e237e9868'
down_revision: Union[str, None] = '47726d0e87e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('position', postgresql.ENUM('PI', 'CO_PI', 'POSTDOC', 'PHD_STUDENT', 'RESEARCH_ENGINEER', 'TECHNICIAN', 'ADMIN', name='researcherposition'), nullable=False),
    sa.Column('contract_type', postgresql.ENUM('DL57', 'CEEC', 'BOLSA_BI', 'BOLSA_BD', 'BOLSA_BPD', 'CLT', 'OTHER', name='contracttype'), nullable=False),
    sa.Column('fte', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('annual_gross_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('productive_hours', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('effort_allocations',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('planned_pm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('planned_fte_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_id', 'project_id', 'work_package_id', 'period_start', name='uq_effort_allocation_researcher_project_wp_period')
    )
    op.create_index(op.f('ix_effort_allocations_project_id'), 'effort_allocations', ['project_id'], unique=False)
    op.create_index(op.f('ix_effort_allocations_researcher_id'), 'effort_allocations', ['researcher_id'], unique=False)
    op.create_table('timesheet_entries',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_id', 'project_id', 'work_package_id', 'date', name='uq_timesheet_entry_researcher_project_wp_date')
    )
    op.create_index(op.f('ix_timesheet_entries_project_id'), 'timesheet_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_researcher_id'), 'timesheet_entries', ['researcher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_entries_researcher_id'), table_name='timesheet_entries')
    op.drop_index(op.f('ix_timesheet_entries_project_id'), table_name='timesheet_entries')
    op.drop_table('timesheet_entries')
    op.drop_index(op.f('ix_effort_allocations_researcher_id'), table_name='effort_allocations')
    op.drop_index(op.f('ix_effort_allocations_project_id'), table_name='effort_allocations')
    op.drop_table('effort_allocations')
    op.drop_table('researchers')
    # ### end Alembic commands ###
