"""create_core_data_model

Revision ID: e67a08ff00f5
Revises: 
Create Date: 2026-03-12 16:52:01.051622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e67a08ff00f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('pic_number', sa.String(length=20), nullable=True),
    sa.Column('legal_name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('org_type', postgresql.ENUM('HES', 'REC', 'PRC', 'PUB', 'OTH', name='org_type'), nullable=True),
    sa.Column('is_sme', sa.Boolean(), nullable=False),
    sa.Column('contact_person', sa.String(length=500), nullable=True),
    sa.Column('bank_account_validated', sa.Boolean(), nullable=False),
    sa.Column('accession_form_signed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pic_number')
    )
    op.create_index(op.f('ix_partners_short_name'), 'partners', ['short_name'], unique=False)
    op.create_table('projects',
    sa.Column('acronym', sa.String(length=50), nullable=False),
    sa.Column('full_title', sa.String(length=500), nullable=False),
    sa.Column('grant_agreement_number', sa.String(length=50), nullable=True),
    sa.Column('programme', postgresql.ENUM('HORIZON_EUROPE', 'DIGITAL_EUROPE', 'ERASMUS_PLUS', 'CEF', 'FCT', name='programme_type'), nullable=False),
    sa.Column('call_identifier', sa.String(length=100), nullable=True),
    sa.Column('cost_model', postgresql.ENUM('ACTUAL_COSTS', 'LUMP_SUM', 'UNIT_COSTS', 'MIXED', name='cost_model_type'), nullable=False),
    sa.Column('role', postgresql.ENUM('COORDINATOR', 'PARTNER', 'ASSOCIATED_PARTNER', name='project_role_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('total_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('eu_contribution', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reporting_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('PROPOSAL', 'NEGOTIATION', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='project_status_type'), nullable=False),
    sa.Column('ec_project_officer', sa.String(length=200), nullable=True),
    sa.Column('internal_cost_center', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_agreement_number')
    )
    op.create_index(op.f('ix_projects_acronym'), 'projects', ['acronym'], unique=False)
    op.create_index(op.f('ix_projects_cost_model'), 'projects', ['cost_model'], unique=False)
    op.create_index(op.f('ix_projects_programme'), 'projects', ['programme'], unique=False)
    op.create_index(op.f('ix_projects_role'), 'projects', ['role'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_partners',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('partner_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partner_eu_contribution', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_partners_partner_id'), 'project_partners', ['partner_id'], unique=False)
    op.create_index(op.f('ix_project_partners_project_id'), 'project_partners', ['project_id'], unique=False)
    op.create_table('work_packages',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wp_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('lead_partner_id', sa.UUID(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('total_pm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', name='wp_status_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_packages_project_id'), 'work_packages', ['project_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('work_package_id', sa.UUID(), nullable=False),
    sa.Column('deliverable_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', postgresql.ENUM('REPORT', 'DEMONSTRATOR', 'DATA', 'SOFTWARE', 'OTHER', name='deliverable_type'), nullable=False),
    sa.Column('dissemination_level', postgresql.ENUM('PU', 'SEN', 'CO', name='dissemination_level_type'), nullable=False),
    sa.Column('lead_partner_id', sa.UUID(), nullable=True),
    sa.Column('due_month', sa.Integer(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('ec_review_status', postgresql.ENUM('PENDING', 'APPROVED', 'REVISION_REQUESTED', 'REJECTED', name='ec_review_status_type'), nullable=False),
    sa.Column('traffic_light', postgresql.ENUM('GREEN', 'AMBER', 'RED', name='traffic_light_type'), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_work_package_id'), 'deliverables', ['work_package_id'], unique=False)
    op.create_table('milestones',
    sa.Column('work_package_id', sa.UUID(), nullable=False),
    sa.Column('milestone_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('due_month', sa.Integer(), nullable=True),
    sa.Column('verification_means', sa.Text(), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('achievement_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_work_package_id'), 'milestones', ['work_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestones_work_package_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_deliverables_work_package_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_work_packages_project_id'), table_name='work_packages')
    op.drop_table('work_packages')
    op.drop_index(op.f('ix_project_partners_project_id'), table_name='project_partners')
    op.drop_index(op.f('ix_project_partners_partner_id'), table_name='project_partners')
    op.drop_table('project_partners')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_role'), table_name='projects')
    op.drop_index(op.f('ix_projects_programme'), table_name='projects')
    op.drop_index(op.f('ix_projects_cost_model'), table_name='projects')
    op.drop_index(op.f('ix_projects_acronym'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_partners_short_name'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
