"""add_financial_models

Revision ID: f321b32341cf
Revises: e67a08ff00f5
Create Date: 2026-03-12 17:38:51.780861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f321b32341cf'
down_revision: Union[str, None] = 'e67a08ff00f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_category_mappings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ec_category', postgresql.ENUM('A_PERSONNEL', 'B_SUBCONTRACTING', 'C1_TRAVEL', 'C2_EQUIPMENT', 'C3_OTHER_GOODS', 'D_OTHER_COSTS', 'E_INDIRECT', name='ec_budget_category_type'), nullable=False),
    sa.Column('university_account_code', sa.String(length=100), nullable=False),
    sa.Column('university_category_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_category_mappings_project_id'), 'budget_category_mappings', ['project_id'], unique=False)
    op.create_table('fund_distributions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('distribution_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('distribution_date', sa.Date(), nullable=False),
    sa.Column('bank_transfer_reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_distributions_partner_id'), 'fund_distributions', ['partner_id'], unique=False)
    op.create_index(op.f('ix_fund_distributions_project_id'), 'fund_distributions', ['project_id'], unique=False)
    op.create_table('expenses',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('ec_category', postgresql.ENUM('A_PERSONNEL', 'B_SUBCONTRACTING', 'C1_TRAVEL', 'C2_EQUIPMENT', 'C3_OTHER_GOODS', 'D_OTHER_COSTS', 'E_INDIRECT', name='ec_budget_category_type'), nullable=True),
    sa.Column('university_account_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date_incurred', sa.Date(), nullable=False),
    sa.Column('reporting_period_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REPORTED', 'AUDITED', name='expense_status_type'), nullable=False),
    sa.Column('ec_eligible', sa.Boolean(), nullable=False),
    sa.Column('supporting_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_partner_id'), 'expenses', ['partner_id'], unique=False)
    op.create_index(op.f('ix_expenses_project_id'), 'expenses', ['project_id'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_work_package_id'), 'expenses', ['work_package_id'], unique=False)
    op.create_table('missions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('researcher_name', sa.String(length=200), nullable=False),
    sa.Column('purpose', postgresql.ENUM('CONSORTIUM_MEETING', 'CONFERENCE', 'SECONDMENT', 'FIELDWORK', 'TRAINING', 'OTHER', name='mission_purpose_type'), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('approval_status', postgresql.ENUM('REQUESTED', 'PI_APPROVED', 'CENTRALLY_APPROVED', 'COMPLETED', 'CANCELLED', name='approval_status_type'), nullable=False),
    sa.Column('travel_costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accommodation_costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('subsistence', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('registration_fees', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ec_eligible', sa.Boolean(), nullable=False),
    sa.Column('supporting_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('university_travel_order', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_project_id'), 'missions', ['project_id'], unique=False)
    op.create_table('procurements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_package_id', sa.UUID(), nullable=True),
    sa.Column('ec_category', postgresql.ENUM('A_PERSONNEL', 'B_SUBCONTRACTING', 'C1_TRAVEL', 'C2_EQUIPMENT', 'C3_OTHER_GOODS', 'D_OTHER_COSTS', 'E_INDIRECT', name='ec_budget_category_type'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=300), nullable=True),
    sa.Column('procurement_method', postgresql.ENUM('DIRECT_PURCHASE', 'THREE_QUOTES', 'PUBLIC_TENDER', 'FRAMEWORK_AGREEMENT', name='procurement_method_type'), nullable=True),
    sa.Column('university_threshold', postgresql.ENUM('BELOW_THRESHOLD', 'SIMPLIFIED', 'FULL_PROCEDURE', name='university_threshold_type'), nullable=True),
    sa.Column('depreciation_applicable', sa.Boolean(), nullable=False),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('eligible_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('invoice_reference', sa.String(length=100), nullable=True),
    sa.Column('supporting_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', postgresql.ENUM('REQUESTED', 'PI_APPROVED', 'PROCUREMENT_APPROVED', 'COMPLETED', name='procurement_approval_status_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurements_project_id'), 'procurements', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurements_project_id'), table_name='procurements')
    op.drop_table('procurements')
    op.drop_index(op.f('ix_missions_project_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_expenses_work_package_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_project_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_partner_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_fund_distributions_project_id'), table_name='fund_distributions')
    op.drop_index(op.f('ix_fund_distributions_partner_id'), table_name='fund_distributions')
    op.drop_table('fund_distributions')
    op.drop_index(op.f('ix_budget_category_mappings_project_id'), table_name='budget_category_mappings')
    op.drop_table('budget_category_mappings')
    # ### end Alembic commands ###
